CC = g++
CFLAGS = -Wall

BIN_DIR = bin
PROG_NAME = $(BIN_DIR)/server

SRC_DIR = src
SERVER = $(SRC_DIR)/server.cpp
MAIN = $(SRC_DIR)/main.cpp $(SERVER)

default:
	$(CC) $(CFLAGS) -o $(PROG_NAME) $(MAIN)
